export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const ADD_ENTRY_SUCCESS = "ADD_ENTRY_SUCCESS";
export const ADD_ENTRY_FAIL = "ADD_ENTRY_FAIL";
export const GET_ENTRY_SUCCESS = "GET_ENTRY_SUCCESS";
export const GET_ENTRY_FAIL = "GET_ENTRY_FAIL";
export const GET_ENTRIES_SUCCESS = "GET_ENTRIES_SUCCESS";
export const GET_ENTRIES_FAIL = "GET_ENTRIES_FAIL";
export const DELETE_ENTRY_SUCCESS = "DELETE_ENTRY_SUCCESS";
export const DELETE_ENTRY_FAIL = "DELETE_ENTRY_FAIL";
export const LOAD_ENTRY = "LOAD_ENTRY";
export const LOAD_ENTRIES = "LOAD_ENTRIES";

export const ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
export const ERROR_INVALID_CREDENTIALS = "ERROR_INVALID_CREDENTIALS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";