export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const ADD_ENTRY_SUCCESS = "ADD_ENTRY_SUCCESS";
export const ADD_ENTRY_FAIL = "ADD_ENTRY_FAIL";
export const GET_ENTRIES_SUCCESS = "GET_ENTRIES_SUCCESS";
export const GET_ENTRIES_FAIL = "GET_ENTRIES_FAIL";

export const ERROR_USER_EXISTS = "ERROR_USER_EXISTS";
export const ERROR_INVALID_CREDENTIALS = "ERROR_INVALID_CREDENTIALS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";